Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Visit me at http://0.0.0.0:5555
No hostname was supplied. Reverting to default 'localhost'
Broker: redis://localhost:6379//

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def process_file(file_id):
    return 1

Registered tasks: 
['api.tasks.process_file',
 'celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap']
Settings: {'cookie_secret': 'SaAxIKntwkIcN_RkyLwr8pEeq827KX7eej59RwHp3PAgaf3Uc3N_kMVGbS_LIkpdWn_xOJyB8nuUJZDN8Awn9g',
 'debug': False,
 'login_url': '/login',
 'static_path': '/home/nikita/.local/lib/python3.8/site-packages/flower/static',
 'static_url_prefix': '/static/',
 'template_path': '/home/nikita/.local/lib/python3.8/site-packages/flower/templates'}
Starting enable events timer...
Capturing events...
No hostname was supplied. Reverting to default 'localhost'
Connected to redis://localhost:6379//
Sending stats inspect command
Sending active_queues inspect command
Sending registered inspect command
No hostname was supplied. Reverting to default 'localhost'
No hostname was supplied. Reverting to default 'localhost'
Sending active inspect command
No hostname was supplied. Reverting to default 'localhost'
Sending reserved inspect command
Sending scheduled inspect command
Sending revoked inspect command
Sending conf inspect command
No hostname was supplied. Reverting to default 'localhost'
No hostname was supplied. Reverting to default 'localhost'
No hostname was supplied. Reverting to default 'localhost'
No hostname was supplied. Reverting to default 'localhost'
No hostname was supplied. Reverting to default 'localhost'
No hostname was supplied. Reverting to default 'localhost'
No hostname was supplied. Reverting to default 'localhost'
Inspect command stats took 1.06s to complete
Inspect command active_queues took 1.06s to complete
Inspect command registered took 1.06s to complete
Inspect command conf took 1.05s to complete
Inspect command reserved took 1.06s to complete
Inspect command scheduled took 1.06s to complete
Inspect command revoked took 1.06s to complete
Inspect command active took 1.07s to complete
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Stopping enable events timer...
Stopping executors...
Stopping event loop...
Visit me at http://0.0.0.0:5555
Broker: redis://localhost:6379/0

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def process_file(file_id):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Registered tasks: 
['api.tasks.process_file',
 'celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap']
Settings: {'cookie_secret': 'kFPRBD9C-HfmdohTZI5VYKseau4xnSKFaN9tS1dU05FZ4Y8uYzDI8tnwoJ_IDWPjSaXJBaOvAhJQrKP_zPRhhQ',
 'debug': False,
 'login_url': '/login',
 'static_path': '/home/nikita/.local/lib/python3.8/site-packages/flower/static',
 'static_url_prefix': '/static/',
 'template_path': '/home/nikita/.local/lib/python3.8/site-packages/flower/templates'}
Starting enable events timer...
Capturing events...
Connected to redis://localhost:6379/0
Sending stats inspect command
Sending active_queues inspect command
Sending registered inspect command
Sending scheduled inspect command
Sending active inspect command
Sending reserved inspect command
Sending revoked inspect command
Sending conf inspect command
Inspect command registered took 1.04s to complete
Inspect command stats took 1.05s to complete
Inspect command revoked took 1.04s to complete
Inspect command active_queues took 1.05s to complete
Inspect command scheduled took 1.05s to complete
Inspect command active took 1.04s to complete
Inspect command reserved took 1.05s to complete
Inspect command conf took 1.04s to complete
Not Found: /
Stopping enable events timer...
Stopping executors...
Stopping event loop...
Visit me at http://0.0.0.0:5555
Broker: redis://localhost:6379/0

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def process_file(file_id):
    return 1

Registered tasks: 
['api.tasks.process_file',
 'celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap']
Settings: {'cookie_secret': '8IAbn_0XjtLhJ1XTWPT-lLWiYqgpQyshpp9zVIjapTEgNrOnVSvaa9DddjBZMIAGDEGRnmrkO2n2pchnFYulpw',
 'debug': False,
 'login_url': '/login',
 'static_path': '/home/nikita/.local/lib/python3.8/site-packages/flower/static',
 'static_url_prefix': '/static/',
 'template_path': '/home/nikita/.local/lib/python3.8/site-packages/flower/templates'}
Starting enable events timer...
Capturing events...
Connected to redis://localhost:6379/0
Sending stats inspect command
Sending active_queues inspect command
Sending registered inspect command
Sending scheduled inspect command
Sending active inspect command
Sending reserved inspect command
Sending revoked inspect command
Sending conf inspect command
Inspect command reserved took 1.04s to complete
Inspect command active_queues took 1.05s to complete
Inspect command scheduled took 1.05s to complete
Inspect command stats took 1.06s to complete
Inspect command revoked took 1.04s to complete
Inspect command registered took 1.06s to complete
Inspect command active took 1.05s to complete
Inspect command conf took 1.04s to complete
Not Found: /media/uploads/New_requierments_Rus_QWvIJQM.pdf
Not Found: /media/uploads/New_requierments_Rus_QWvIJQM.pdf
Not Found: /media/uploads/New_requierments_Rus_INQ0Qo8.pdf
Not Found: /media/uploads/New_requierments_Rus_INQ0Qo8.pdf
Sending stats inspect command
Sending active_queues inspect command
Sending registered inspect command
Sending scheduled inspect command
Sending active inspect command
Sending reserved inspect command
Sending revoked inspect command
Sending conf inspect command
Inspect command active_queues took 0.04s to complete
Inspect command stats took 0.06s to complete
Inspect command scheduled took 0.05s to complete
Inspect command registered took 0.06s to complete
Inspect command reserved took 0.04s to complete
Inspect command revoked took 0.03s to complete
Inspect command conf took 0.03s to complete
Inspect command active took 0.06s to complete
Failed to capture events: 'Connection closed by server.', trying again in 1 seconds.
Connection closed by server.
Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/flower/events.py", line 183, in run
    recv.capture(limit=None, timeout=None, wakeup=True)
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/events/receiver.py", line 91, in capture
    for _ in self.consume(limit=limit, timeout=timeout, wakeup=wakeup):
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/mixins.py", line 196, in consume
    conn.drain_events(timeout=safety_interval)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 588, in get
    ret = self.handle_event(fileno, event)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 570, in handle_event
    return self.on_readable(fileno), self
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 566, in on_readable
    chan.handlers[type]()
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 910, in _receive
    ret.append(self._receive_one(c))
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 920, in _receive_one
    response = c.parse_response()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/client.py", line 1542, in parse_response
    response = self._execute(conn, try_read)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/client.py", line 1518, in _execute
    return conn.retry.call_with_retry(
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 49, in call_with_retry
    fail(error)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/client.py", line 1520, in <lambda>
    lambda error: self._disconnect_raise_connect(conn, error),
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/client.py", line 1507, in _disconnect_raise_connect
    raise error
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/client.py", line 1519, in <lambda>
    lambda: command(*args, **kwargs),
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/client.py", line 1540, in try_read
    return conn.read_response(disconnect_on_error=False)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 359, in _read_response
    raw = self._buffer.readline()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 262, in readline
    self._read_from_socket()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 215, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Failed to capture events: 'Error 111 connecting to localhost:6379. Connection refused.', trying again in 2 seconds.
Error 111 connecting to localhost:6379. Connection refused.
Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 951, in create_channel
    return self._avail_channels.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 707, in connect
    sock = self.retry.call_with_retry(
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 708, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 1006, in _connect
    raise err
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 994, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 472, in _reraise_as_library_errors
    yield
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 459, in _ensure_connection
    return retry_over_time(
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/utils/functional.py", line 318, in retry_over_time
    return fun(*args, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 941, in _connection_factory
    self._connection = self._establish_connection()
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 867, in _establish_connection
    conn = self.transport.establish_connection()
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 975, in establish_connection
    self._avail_channels.append(self.create_channel(self))
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 953, in create_channel
    channel = self.Channel(connection)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 741, in __init__
    self.client.ping()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/commands/core.py", line 1205, in ping
    return self.execute_command("PING", **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 1461, in get_connection
    connection.connect()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 713, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to localhost:6379. Connection refused.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/flower/events.py", line 178, in run
    recv = EventReceiver(conn,
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/events/receiver.py", line 39, in __init__
    self.channel = maybe_channel(channel)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 1117, in maybe_channel
    return channel.default_channel
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 960, in default_channel
    self._ensure_connection(**conn_opts)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 459, in _ensure_connection
    return retry_over_time(
  File "/usr/lib/python3.8/contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 476, in _reraise_as_library_errors
    raise ConnectionError(str(exc)) from exc
kombu.exceptions.OperationalError: Error 111 connecting to localhost:6379. Connection refused.
Capturing events...
Connected to redis://localhost:6379/0
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/celery.py changed, reloading.

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Watching for file changes with StatReloader
Sending stats inspect command
Sending active_queues inspect command
Sending registered inspect command
Sending scheduled inspect command
Sending active inspect command
Sending reserved inspect command
Sending revoked inspect command
Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection closed by server.')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/flower/inspector.py", line 37, in _inspect
    getattr(inspect, method)()
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 338, in active_queues
    return self._request('active_queues')
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/pidbox.py", line 346, in _broadcast
    return self._collect(reply_ticket, limit=limit,
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/pidbox.py", line 388, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 581, in get
    self._register_BRPOP(channel)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 522, in _register_BRPOP
    channel._brpop_start()
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 954, in _brpop_start
    self.client.connection.send_command(*command_args)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 855, in send_command
    self.send_packed_command(
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 828, in send_packed_command
    self.check_health()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 820, in check_health
    self.retry.call_with_retry(self._send_ping, self._ping_failed)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 51, in call_with_retry
    raise error
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 810, in _send_ping
    if str_if_bytes(self.read_response()) != "PONG":
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 359, in _read_response
    raw = self._buffer.readline()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 262, in readline
    self._read_from_socket()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 215, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Sending conf inspect command
Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection closed by server.')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/flower/inspector.py", line 37, in _inspect
    getattr(inspect, method)()
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 243, in stats
    return self._request('stats')
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/pidbox.py", line 346, in _broadcast
    return self._collect(reply_ticket, limit=limit,
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/pidbox.py", line 388, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 581, in get
    self._register_BRPOP(channel)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 522, in _register_BRPOP
    channel._brpop_start()
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 954, in _brpop_start
    self.client.connection.send_command(*command_args)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 855, in send_command
    self.send_packed_command(
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 828, in send_packed_command
    self.check_health()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 820, in check_health
    self.retry.call_with_retry(self._send_ping, self._ping_failed)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 51, in call_with_retry
    raise error
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 810, in _send_ping
    if str_if_bytes(self.read_response()) != "PONG":
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 359, in _read_response
    raw = self._buffer.readline()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 262, in readline
    self._read_from_socket()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 215, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Inspect command registered took 0.04s to complete
Inspect command scheduled took 0.04s to complete
Inspect command active took 0.03s to complete
Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection closed by server.')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/flower/inspector.py", line 37, in _inspect
    getattr(inspect, method)()
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 177, in reserved
    return self._request('reserved')
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/pidbox.py", line 346, in _broadcast
    return self._collect(reply_ticket, limit=limit,
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/pidbox.py", line 388, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 581, in get
    self._register_BRPOP(channel)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 522, in _register_BRPOP
    channel._brpop_start()
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 954, in _brpop_start
    self.client.connection.send_command(*command_args)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 855, in send_command
    self.send_packed_command(
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 828, in send_packed_command
    self.check_health()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 820, in check_health
    self.retry.call_with_retry(self._send_ping, self._ping_failed)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 51, in call_with_retry
    raise error
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 810, in _send_ping
    if str_if_bytes(self.read_response()) != "PONG":
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 359, in _read_response
    raw = self._buffer.readline()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 262, in readline
    self._read_from_socket()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 215, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
Inspect command revoked took 0.03s to complete
Future exception was never retrieved
future: <Future finished exception=ConnectionError('Connection closed by server.')>
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/flower/inspector.py", line 37, in _inspect
    getattr(inspect, method)()
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 386, in conf
    return self._request('conf', with_defaults=with_defaults)
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 106, in _request
    return self._prepare(self.app.control.broadcast(
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/app/control.py", line 776, in broadcast
    return self.mailbox(conn)._broadcast(
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/pidbox.py", line 346, in _broadcast
    return self._collect(reply_ticket, limit=limit,
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/pidbox.py", line 388, in _collect
    self.connection.drain_events(timeout=timeout)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/connection.py", line 341, in drain_events
    return self.transport.drain_events(self.connection, **kwargs)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/virtual/base.py", line 997, in drain_events
    get(self._deliver, timeout=timeout)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 581, in get
    self._register_BRPOP(channel)
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 522, in _register_BRPOP
    channel._brpop_start()
  File "/home/nikita/.local/lib/python3.8/site-packages/kombu/transport/redis.py", line 954, in _brpop_start
    self.client.connection.send_command(*command_args)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 855, in send_command
    self.send_packed_command(
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 828, in send_packed_command
    self.check_health()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 820, in check_health
    self.retry.call_with_retry(self._send_ping, self._ping_failed)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 51, in call_with_retry
    raise error
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 810, in _send_ping
    if str_if_bytes(self.read_response()) != "PONG":
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 882, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 349, in read_response
    result = self._read_response(disable_decoding=disable_decoding)
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 359, in _read_response
    raw = self._buffer.readline()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 262, in readline
    self._read_from_socket()
  File "/home/nikita/.local/lib/python3.8/site-packages/redis/connection.py", line 215, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/celery.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/celery.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/celery.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/celery.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/celery.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/celery.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def add(x, y):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def add(x, y):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def add(x, y):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def xsum(numbers):
    return 1


def add(x, y):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def mul(x, y):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/tasks.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
Signal handler <bound method DjangoFixup.on_import_modules of <celery.fixups.django.DjangoFixup object at 0x7f674f046310>> raised: ModuleNotFoundError("No module named 'your_app'")
Traceback (most recent call last):
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/utils/dispatch/signal.py", line 276, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/fixups/django.py", line 97, in on_import_modules
    self.worker_fixup.validate_models()
  File "/home/nikita/.local/lib/python3.8/site-packages/celery/fixups/django.py", line 137, in validate_models
    run_checks()
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/usr/local/lib/python3.8/dist-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/usr/local/lib/python3.8/dist-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.8/dist-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/urls.py", line 6, in <module>
    path('api/', include('api.urls', namespace='api')),
  File "/usr/local/lib/python3.8/dist-packages/django/urls/conf.py", line 38, in include
    urlconf_module = import_module(urlconf_module)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/mnt/d/Documents/Dev/picasso/picasso_test/api/urls.py", line 2, in <module>
    from .views import FileUploadView
  File "/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py", line 6, in <module>
    from your_app.tasks import process_file
ModuleNotFoundError: No module named 'your_app'
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def xmap(task, it):
    return 1


def process_file(file_id):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1

Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py", line 23, in post
    with task.when_done() as result:
AttributeError: 'AsyncResult' object has no attribute 'when_done'
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def process_file(file_id):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1

Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py", line 23, in post
    with task as result:
AttributeError: __enter__
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
Stopping enable events timer...
Stopping executors...
Stopping event loop...
Visit me at http://0.0.0.0:5555
Broker: redis://localhost:6379/0

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def process_file(file_id):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Registered tasks: 
['api.tasks.process_file',
 'celery.accumulate',
 'celery.backend_cleanup',
 'celery.chain',
 'celery.chord',
 'celery.chord_unlock',
 'celery.chunks',
 'celery.group',
 'celery.map',
 'celery.starmap',
 'picasso_test.celery.debug_task']
Settings: {'cookie_secret': 'UOKBvl0dA3_QbWSoeWoldOJrBg7bwkgTjXBohxqV5jbzL3filfptHbjbiZzmiI8JNGUoA7IURLI6IWnNIojHzw',
 'debug': False,
 'login_url': '/login',
 'static_path': '/home/nikita/.local/lib/python3.8/site-packages/flower/static',
 'static_url_prefix': '/static/',
 'template_path': '/home/nikita/.local/lib/python3.8/site-packages/flower/templates'}
Starting enable events timer...
Capturing events...
Connected to redis://localhost:6379/0
Sending stats inspect command
Sending active_queues inspect command
Sending registered inspect command
Sending scheduled inspect command
Sending active inspect command
Sending reserved inspect command
Sending revoked inspect command
Sending conf inspect command
Inspect command registered took 1.04s to complete
Inspect method registered failed
Inspect command stats took 1.04s to complete
Inspect method stats failed
Inspect command reserved took 1.03s to complete
Inspect method reserved failed
Inspect command active took 1.04s to complete
Inspect method active failed
Inspect command scheduled took 1.05s to complete
Inspect method scheduled failed
Inspect command active_queues took 1.05s to complete
Inspect command revoked took 1.04s to complete
Inspect command conf took 1.04s to complete
Inspect method active_queues failed
Inspect method revoked failed
Inspect method conf failed
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def xmap(task, it):
    return 1


def process_file(file_id):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def process_file(file_id):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def process_file(file_id):
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def debug_task(self):
    return 1

404 GET /worker/celery%40DESKTOP-8QUOGNA (::1): Unknown worker 'celery@DESKTOP-8QUOGNA'
Sending stats inspect command
Sending active_queues inspect command
Sending registered inspect command
Sending scheduled inspect command
Sending active inspect command
Sending reserved inspect command
Sending revoked inspect command
Sending conf inspect command
Inspect command stats took 0.02s to complete
Inspect command registered took 0.02s to complete
Inspect command active_queues took 0.02s to complete
Inspect command scheduled took 0.01s to complete
Inspect command active took 0.01s to complete
Inspect command reserved took 0.01s to complete
Inspect command revoked took 0.01s to complete
Inspect command conf took 0.02s to complete
/mnt/d/Documents/Dev/picasso/picasso_test/api/serializers.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/urls.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/urls.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/celery.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def process_file(file_id):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def process_file(file_id):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/tasks.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/tasks.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/tasks.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/tasks.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 92, in save
    name = self.field.generate_filename(self.instance, name)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 332, in generate_filename
    filename = self.upload_to(instance, filename)
TypeError: file_upload_path() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py", line 17, in post
    file_serializer.save()
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 981, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `File.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `File.objects.create()`. You may need to make the field read-only, or override the FileSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 92, in save
    name = self.field.generate_filename(self.instance, name)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 332, in generate_filename
    filename = self.upload_to(instance, filename)
TypeError: file_upload_path() takes 1 positional argument but 2 were given


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 92, in save
    name = self.field.generate_filename(self.instance, name)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 332, in generate_filename
    filename = self.upload_to(instance, filename)
TypeError: file_upload_path() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py", line 17, in post
    file_serializer.save()
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 981, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `File.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `File.objects.create()`. You may need to make the field read-only, or override the FileSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 92, in save
    name = self.field.generate_filename(self.instance, name)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 332, in generate_filename
    filename = self.upload_to(instance, filename)
TypeError: file_upload_path() takes 1 positional argument but 2 were given

/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def process_file(file_id):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Internal Server Error: /api/upload/
/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def process_file(file_id):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def process_file(file_id):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def process_file(file_id):
    return 1

Internal Server Error: /api/upload/
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 92, in save
    name = self.field.generate_filename(self.instance, name)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 332, in generate_filename
    filename = self.upload_to(instance, filename)
TypeError: file_upload_path() takes 1 positional argument but 2 were given

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.8/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/decorators/csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py", line 17, in post
    file_serializer.save()
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 212, in save
    self.instance = self.create(validated_data)
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 981, in create
    raise TypeError(msg)
TypeError: Got a `TypeError` when calling `File.objects.create()`. This may be because you have a writable field on the serializer class that is not a valid argument to `File.objects.create()`. You may need to make the field read-only, or override the FileSerializer.create() method to handle this correctly.
Original exception was:
 Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/rest_framework/serializers.py", line 962, in create
    instance = ModelClass._default_manager.create(**validated_data)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 658, in create
    obj.save(force_insert=True, using=self.db)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 814, in save
    self.save_base(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 877, in save_base
    updated = self._save_table(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1020, in _save_table
    results = self._do_insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/base.py", line 1061, in _do_insert
    return manager._insert(
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/manager.py", line 87, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/query.py", line 1805, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1821, in execute_sql
    for sql, params in self.as_sql():
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1745, in as_sql
    value_rows = [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1746, in <listcomp>
    [
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1747, in <listcomp>
    self.prepare_value(field, self.pre_save_val(field, obj))
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/sql/compiler.py", line 1695, in pre_save_val
    return field.pre_save(obj, add=True)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 317, in pre_save
    file.save(file.name, file.file, save=False)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 92, in save
    name = self.field.generate_filename(self.instance, name)
  File "/usr/local/lib/python3.8/dist-packages/django/db/models/fields/files.py", line 332, in generate_filename
    filename = self.upload_to(instance, filename)
TypeError: file_upload_path() takes 1 positional argument but 2 were given

/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def process_file(file_id):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/models.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def process_file(file_id):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Internal Server Error: /api/upload/
Internal Server Error: /api/upload/
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

Internal Server Error: /api/upload/
/mnt/d/Documents/Dev/picasso/picasso_test/api/views.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/api/tasks.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader
/mnt/d/Documents/Dev/picasso/picasso_test/picasso_test/settings.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader

def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1


def process_file(file_id):
    return 1


def group(self, tasks, result, group_id, partial_args, add_to_parent=0):
    return 1


def process_file(file_id):
    return 1


def xmap(task, it):
    return 1


def chain(*args, **kwargs):
    return 1


def xstarmap(task, it):
    return 1


def backend_cleanup():
    return 1


def chord(self, header, body, partial_args=0, interval=1, countdown=2, max_retries=3, eager=4, **kwargs):
    return 1


def accumulate(self, *args, **kwargs):
    return 1


def chunks(task, it, n):
    return 1


def unlock_chord(self, group_id, callback, interval=0, max_retries=1, result=2, Result=3, GroupResult=4, result_from_tuple=5, **kwargs):
    return 1

